/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#3c2f00",
        "surface-bright": "#3a3939",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#534304",
        "surface": "#131313",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bdcabc",
        "on-secondary-fixed-variant": "#574500",
        "primary-fixed-dim": "#66dd8b",
        "on-secondary-fixed": "#241a00",
        "inverse-on-surface": "#313030",
        "on-primary-container": "#005025",
        "surface-container": "#201f1f",
        "surface-variant": "#353534",
        "primary": "#6ee591",
        "tertiary-fixed": "#fbe194",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed-variant": "#564506",
        "outline-variant": "#3e4a3f",
        "on-primary": "#003919",
        "primary-container": "#50c878",
        "on-secondary": "#3c2f00",
        "background": "#131313",
        "error": "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "tertiary-container": "#c8b069",
        "on-error": "#690005",
        "secondary-container": "#af8d11",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#ffe088",
        "outline": "#879487",
        "tertiary": "#e5cc81",
        "primary-fixed": "#83fba5",
        "surface-tint": "#66dd8b",
        "on-primary-fixed-variant": "#005227",
        "secondary": "#e9c349",
        "on-primary-fixed": "#00210c",
        "secondary-fixed-dim": "#e9c349",
        "inverse-primary": "#006d36",
        "tertiary-fixed-dim": "#ddc57b",
        "on-secondary-container": "#342800",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#231b00"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
         "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
